import "@/styles/globals.css";

import { type Metadata } from "next";

import SidebarLayout from "@/components/sidebar/sidebar";
import { auth } from "@/server/auth";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  if (session?.user) {
    console.log(session.user);
    return (
      <SidebarLayout
        user={{
          avatar: session.user.image!,
          name: session.user.name!,
          email: session.user.email!,
        }}
      >
        {children}
        <Toaster />
      </SidebarLayout>
    );
  }
}
